# Generated by Django 4.0.3 on 2022-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurLabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2018', 2018), ('2015', 2015), ('2017', 2017), ('2023', 2023), ('2019', 2019), ('2016', 2016), ('2021', 2021), ('2020', 2020), ('2022', 2022)], max_length=30, unique=True),
        ),
    ]
