# Generated by Django 4.0.3 on 2022-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ourlabtopic_alter_publicationsyears_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('MS Students', 'MS Students'), ('Research Collaborators', 'Research Collaborators'), ('Professor', 'Professor'), ('Research Professor', 'Research Professor'), ('PhD Students', 'PhD Students'), ('Undergraduate', 'Undergraduate')], max_length=40),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2018', 2018), ('2017', 2017), ('2019', 2019), ('2022', 2022), ('2020', 2020), ('2021', 2021), ('2015', 2015), ('2016', 2016), ('2023', 2023)], max_length=30, unique=True),
        ),
    ]
